from fastapi import APIRouter, Depends, HTTPException, Request, Query
from sqlalchemy.orm import Session
from decimal import Decimal
import math

from backend.dependencies import get_db, get_current_user
from backend.models import User
from backend.schemas import (
    GenerateLinkRequest,
    DeeplinkResponse,
    AffiliateLinkResponse,
    PaginatedResponse
)
from backend.services.affiliate_service import generate_user_affiliate_link, get_user_links_paginated

router = APIRouter(prefix="/api/affiliate", tags=["Affiliate Tracking"])

@router.post("/generate", response_model=DeeplinkResponse)
def generate_link(
    request: GenerateLinkRequest,
    req_obj: Request,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user)
):
    """
    Generates a tracked affiliate deeplink with aff_sub1 to aff_sub5 parameters.
    Includes rate limiting and fraud checks. Requires authentication.
    """
    try:
        client_ip = req_obj.client.host if req_obj.client else None
        db_link = generate_user_affiliate_link(
            db=db,
            user=current_user,
            product_url=str(request.product_url),
            offer_id=request.offer_id,
            ip_address=client_ip
        )
        
        # Detect merchant and cashback percentage from settings
        from backend.repositories.settings_repository import SettingsRepository
        from urllib.parse import urlparse
        
        domain = urlparse(db_link.original_url).netloc.lower()
        merchant = "Shopee" if "shopee" in domain else "Lazada" if "lazada" in domain else "TikTok" if "tiktok" in domain else "Default"
        
        settings_repo = SettingsRepository(db)
        rate_val = settings_repo.get_cashback_percentage_val(merchant)
        admin_share = Decimal("100.00") - rate_val
        
        return DeeplinkResponse(
            success=True,
            deeplink=db_link.deeplink,
            tracking_id=db_link.tracking_id,
            merchant=merchant,
            cashback_rate=f"{rate_val}%",
            estimated_info=f"✨ You earn {rate_val}% cashback of merchant commission on this {merchant} link (Admin retains {admin_share}%)",
            aff_sub1=db_link.aff_sub1,
            aff_sub2=db_link.aff_sub2
        )
    except HTTPException as he:
        raise he
    except Exception as e:
        raise HTTPException(status_code=400, detail=str(e))

@router.get("/my-links", response_model=PaginatedResponse[AffiliateLinkResponse])
def get_my_links(
    page: int = Query(default=1, ge=1),
    limit: int = Query(default=20, ge=1, le=100),
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user)
):
    """Retrieves paginated affiliate links generated by the current user."""
    items, total = get_user_links_paginated(db=db, user_id=current_user.id, page=page, limit=limit)
    total_pages = math.ceil(total / limit) if total > 0 else 1
    return PaginatedResponse(
        items=items,
        total=total,
        page=page,
        limit=limit,
        total_pages=total_pages
    )

@router.get("/r/{tracking_id}")
def redirect_and_track_click(tracking_id: str, db: Session = Depends(get_db)):
    """
    Click Tracker: Increments link click count and redirects visitor to the affiliate deeplink.
    """
    from fastapi.responses import RedirectResponse
    from backend.repositories.affiliate_repository import AffiliateRepository
    
    affiliate_repo = AffiliateRepository(db)
    link = affiliate_repo.get_by_tracking_id(tracking_id)
    if not link:
        raise HTTPException(status_code=404, detail="Affiliate link not found")
    
    # Increment clicks
    link.clicks = (link.clicks or 0) + 1
    db.commit()
    
    return RedirectResponse(url=link.deeplink, status_code=307)

@router.api_route("/track-click/{tracking_id}", methods=["GET", "POST"])
def record_direct_click(tracking_id: str, db: Session = Depends(get_db)):
    """
    Direct Click Tracker: Async background click logger when user clicks a direct Involve Asia URL.
    """
    from backend.repositories.affiliate_repository import AffiliateRepository
    affiliate_repo = AffiliateRepository(db)
    link = affiliate_repo.get_by_tracking_id(tracking_id)
    if not link:
        raise HTTPException(status_code=404, detail="Affiliate link not found")
    
    link.clicks = (link.clicks or 0) + 1
    db.commit()
    return {"success": True, "clicks": link.clicks}
